version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data

      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=table
    ports:
      - "4572:4572" # s3
      - "4576:4576" # sqs
    volumes:
      - ./localstack/init.sh:/docker-entrypoint-initaws.d/docker-entrypoint.sh

  glue:
    image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
    volumes:
      - ./aws:/home/glue_user/.aws
      - ./workspace:/home/glue_user/workspace
    environment:
      - DISABLE_SSL=true 
    ports:
      - "4040:4040"
      - "18080:18080"
    stdin_open: true